config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root to: "dashboards#index"
    resources :articles, except: [:show]
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :notifications, only: [:index, :new, :create, :destroy]
    resources :passwords, only: [:edit, :update]
    resources :profiles, only: [:show, :edit, :update]
    resources :users, except: [:show]
    resources :trashes, only: [:index, :edit, :destroy]
  end

  resources :articles, only: [:show]
  resources :categories, only: [:index, :show]

  get "popular" => "categories#index"
  get "device" => "static_pages#device"
  get "test" => "static_pages#google"
  get "test3" => "static_pages#google3"
  get "test2" => "static_pages#google2"
  get "article_banner" => "static_pages#article_banner"
  get "right_banner" => "static_pages#right_banner"
  get "advertising" => "static_pages#advertising"

  devise_for :users
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_paranoid
  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: true
  validate :schedule_at_must_greater_than_current_datetime

  scope :on_schedule, ->{where("schedule_at <= ? and post_status = ?",
    Time.zone.now, Settings.post_status.pending)}
  scope :draft, ->{where post_status: Settings.post_status.draft}
  scope :pending, ->{where post_status: Settings.post_status.pending}
  scope :published, ->{where post_status: Settings.post_status.published}

  scope :find_published_articles, ->limit, offset, category_id{
    joins(:category).where("post_status = ? AND category_id = ?",
        Settings.post_status.published, category_id)
      .order("published_at DESC")
      .limit(limit)
      .offset(offset)
  }

  scope :find_similar_articles, ->limit, except, category_id{
    joins(:category).where("post_status = ? AND category_id = ? AND articles.id <> ?",
      Settings.post_status.published, category_id, except)
    .order("published_at DESC")
    .limit(limit)}

  scope :select_popular, ->limit, except{where("post_status = ? AND articles.id <> ?",
      Settings.post_status.published, except)
    .order("view DESC")
    .limit(limit)}

  after_restore :update_post_status, if: :pending?

  def schedule_at_must_greater_than_current_datetime
    return if schedule_at.blank?
    errors.add :schedule_at, I18n.t("validate.datetime_error") if schedule_at < Time.zone.now
  end

  def pending?
    post_status == Settings.post_status.pending
  end

  def update_post_status
    if schedule_at <= Time.zone.now
      update_attributes post_status: Settings.post_status.draft,
        schedule_at: nil
    end
  end

  def update_view_number
    view = self.view || 0
    update_attributes view: view + 1
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout "admin/application"
  before_action :authenticate_user!
  before_action :get_article_status, only: [:create, :update]
  before_action :find_article_by_params, only: [:edit, :update, :destroy]
  before_action only: [:edit, :update] do
    correct_user? @article.user
  end
  before_action :admin_or_correct_user, only: [:destroy]

  def index
    @search = Article.search params[:q]
    @articles = @search.result
      .paginate(page: params[:page], per_page: Settings.per_page)
      .order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new article_params
    if Settings.commit.preview == params[:commit]
      render "articles/preview"
    elsif @article.save
      redirect_to admin_articles_path, notice: flash_message("created")
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if Settings.commit.preview == params[:commit]
      render "articles/preview"
    elsif @article.update_attributes article_params
      redirect_to admin_articles_path, notice: flash_message("created")
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to request.referrer || root_url, notice: t("flashs.messages.move_to_trash")
  end

  private
  def article_params
    params.require(:article).permit :title, :content, :image, :image_cache,
      :audio_url, :post_status, :category_id, :schedule_at, :published_at
  end

  def get_article_status
    commit = params[:commit]

    if Settings.commit.save_draft == commit
      params[:article][:post_status] = Settings.post_status.draft
      params[:article][:schedule_at] = ""
    elsif Settings.commit.publish == commit
      params[:article][:post_status] = Settings.post_status.published
      params[:article][:schedule_at] = ""
      params[:article][:published_at] = Time.zone.now
    elsif Settings.commit.schedule == commit
      params[:article][:post_status] = Settings.post_status.pending
    elsif Settings.commit.unpublish == commit
      params[:article][:post_status] = Settings.post_status.draft
      params[:article][:published_at] = ""
    elsif Settings.commit.preview == commit
      params[:article][:published_at] = Time.zone.now
    end
  end

  def find_article_by_params
    @article = Article.find params[:id]
    @article_state = Article.find params[:id]
  end

  def admin_or_correct_user
    redirect_to admin_root_path unless current_user.admin? || correct_user?(@article.user)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :update_view_number, only:[:show]

  def show
    @category_id = @article.category.id
    @articles = Article.find_similar_articles 5, @article.id, @category_id
  end

  private
  def update_view_number
    @article = Article.find params[:id]
    @article.update_view_number
  end
end

app/views/admin/articles/_article.html.erb
<tr>
  <td><%= article.title %></td>
  <td><%= article.view %></td>
  <td><%= link_to article.user.name, admin_profile_path(article.user) %></td>
  <td><%= article.category.name %></td>
  <td><%= l article.created_at, format: :default %></td>
  <td><%= article.post_status %></td>
  <td align="center">
    <% if current_user? article.user %>
      <%= link_to edit_admin_article_path(article), class: "btn-icon",
        data: {no_turbolink: true}  do %>
        <i class="fa fa-pencil-square-o"></i>
        <%= t("article.admin.actions.edit") %>
      <% end %>
    <% end %>

    <% if current_user.admin? || current_user?(article.user) %>
      <%= link_to admin_article_path(article), method: :delete,
        data:{confirm: t("custom.confirm_trash")}, class: "btn-icon" do %>
        <i class="fa fa-trash-o"></i>
        <%= t("article.admin.actions.move_to_trash") %>
      <% end %>
    <% end %>

    <%= link_to article, target: "_blank" do %>
      <i class="fa fa-eye"></i>
      <%= t("article.admin.actions.preview") %>
    <% end %>
  </td>
</tr>

app/views/admin/articles/_article_status_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t "article.admin.panel_status" %></h3>
  </div>
  <div class="panel-body">
    <table>
      <tr>
        <td><b><%= t "article.admin.status" %></b> &nbsp;&nbsp;</td>
        <td><%= @article_state.post_status %></td>
      </tr>
      <tr>
        <% if Settings.post_status.pending == @article_state.post_status %>
          <td><b><%= t "article.admin.schedule_at" %></b> &nbsp;&nbsp;</td>
          <td><%= l @article_state.schedule_at, format: :default %></td>
        <% elsif Settings.post_status.published == @article_state.post_status  %>
          <td><b><%= t "article.admin.published_at" %></b> &nbsp;&nbsp;</td>
          <td><%= l @article_state.published_at, format: :default %></td>
        <% end %>
      </tr>
    </table>
  </div>
</div>

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article], html: {multipart: true} do |f| %>
  <div class="row" id="articles">
    <div class="col-md-8">
      <%= render "shared/errors_messages", object: @article %>
      <p><%= f.label :title %></p>
      <p><%= f.text_field :title, class: "form-control" %></p>
      <p><%= f.label :category %></p>
      <p><%= f.collection_select :category_id, Category.all, :id, :name, {},
        class: "form-control" %></p>
      <p><%= f.label :content %></p>
      <p><%= f.cktext_area :content, ckeditor: {toolbar: :full} %></p>
      <p><%= f.label :audio_url %></p>
      <p><%= f.text_field :audio_url, class: "form-control" %></p>
      <p><%= f.label :image %></p>
      <p>
        <%= image_tag @article.image_url, width: "50%" if @article.image? %>
        <%= f.file_field :image, class: "form-control" %>
        <%= f.hidden_field :image_cache %>
      </p>
    </div>

    <div class="col-md-4">
      <% unless @article.new_record? %>
        <%= render "article_status_panel" %>
      <% end %>
      <%= render "publish_panel", f: f %>
    </div>

  </div>
<% end %>

app/views/admin/articles/_form_filter.html.erb
<div class="row">
  <div class="col-md-12">

    <div id="filter">
      <%= search_form_for @search, url: url, method: :get do |f| %>
        <div class="row">
          <div class="col-md-4 title">
            <%= f.text_field :title_cont, class: "form-control",
              placeholder: t("article.admin.list.header.title") %>
          </div>
          <div class="col-md-2 author">
            <%= f.collection_select :user_id_eq, User.all, :id, :name,
              {include_blank: t("article.admin.all_authors")}, class: "form-control" %>
          </div>
          <div class="col-md-2 category">
            <%= f.collection_select :category_id_eq, Category.all, :id, :name,
              {include_blank: t("article.admin.all_categories")}, class: "form-control" %>
          </div>
          <div class="col-md-2 status">
            <%= f.collection_select :post_status_cont, Settings.post_status, :first, :last,
              {include_blank: t("article.admin.all_status")}, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 post-date">
            <div class="form-group">
              <div class='input-group date' id='datetimepicker1'>
                <%=  f.text_field :created_at_gteq,
                  value: (params[:q][:created_at_gteq] if params[:q].present?),
                  class: "datetimepicker1 form-control",
                  placeholder: t("article.admin.min_post_date") %>
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-4 post-date">
            <div class="form-group">
              <div class='input-group date' id='datetimepicker2'>
                <%=  f.text_field :created_at_lteq,
                  value: (params[:q][:created_at_lteq] if params[:q].present?),
                  class: "datetimepicker2 form-control",
                  placeholder: t("article.admin.max_post_date") %>
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-1 action">
            <%= f.submit t("article.admin.buttons.filter"), class: "btn btn-warning pull-right" %>
          </div>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/admin/articles/_publish_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t "article.admin.panel_title" %></h3>
  </div>
  <div class="panel-body">
    <% if @article.new_record? %>
      <%= f.submit t("article.admin.actions.save_draft"), class: "btn btn-default" %>
      <%= render "schedule_form", f: f %>
    <% elsif Settings.post_status.published == @article_state.post_status %>
      <%= f.submit t("article.admin.actions.update"), class: "btn btn-default" %>
      <%= f.submit t("article.admin.actions.preview"), class: "btn btn-primary" %>
      <%= f.submit t("article.admin.actions.unpublish"), class: "btn btn-success" %>
    <% elsif Settings.post_status.pending == @article_state.post_status  %>
      <%= f.submit t("article.admin.actions.update"), class: "btn btn-default" %>
      <%= f.submit t("article.admin.actions.save_draft"), class: "btn btn-default" %>
      <%= render "schedule_form", f: f %>
    <% else %>
      <%= f.submit t("article.admin.actions.update"), class: "btn btn-default" %>
      <%= render "schedule_form", f: f %>
    <% end %>
  </div>
</div>

app/views/admin/articles/_schedule_form.html.erb
<%= f.submit t("article.admin.actions.preview"), class: "btn btn-primary" %>
<%= f.submit t("article.admin.actions.publish"), class: "btn btn-success" %>
<div class="schedule">
  <div class="form-group">
    <div class="input-group date" id="datetimepicker3">
      <%=  f.text_field :schedule_at, class: "datetimepicker3 form-control" %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>
  <%= f.submit t("article.admin.actions.schedule"), class: "btn btn-warning btn-schedule" %>
</div>

app/views/admin/articles/edit.html.erb
<%= provide :title, t("article.admin.title.post_edit") %>
<h3><%= t "article.admin.title.post_edit" %></h3>
<hr>
<%= render "form" %>

app/views/admin/articles/index.html.erb
<%= provide :title, t("article.admin.title.header") %>
<div id="articles">
  <h2 class="title">
    <%= t "article.admin.title.header" %>
    <%= link_to new_admin_article_path, class: "btn btn-primary pull-right",
      data: {no_turbolink: true} do %>
      <i class="fa fa-plus-square"></i> &nbsp;
      <%= t("article.admin.buttons.add") %>
    <% end %>
  </h2>
  <hr>
  <div class="form-filter">
    <%= render "form_filter", url: admin_articles_path %>
  </div>
  <hr>
  <table class="table table-bordered">
    <thead>
      <th width="25%"><%= t "article.admin.list.header.title" %></th>
      <th width="5%"><%= t "article.admin.list.header.views" %></th>
      <th width="10%"><%= t "article.admin.list.header.author" %></th>
      <th width="10%"><%= t "article.admin.list.header.category" %></th>
      <th width="15%"><%= t "article.admin.list.header.posted_date" %></th>
      <th width="10%"><%= t "article.admin.list.header.status" %></th>
      <th width="25%"></th>
    </thead>
    <tbody>
      <%= render @articles %>
    </tbody>
  </table>
  <%= will_paginate @articles %>
</div>

app/views/admin/articles/new.html.erb
<%= provide :title, t("article.admin.title.post_new") %>
<h3><%= t "article.admin.title.post_new" %></h3>
<hr>
<%= render "form" %>