config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root to: "dashboards#index"
    resources :articles, except: [:show]
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :notifications, only: [:index, :new, :create, :destroy]
    resources :passwords, only: [:edit, :update]
    resources :profiles, only: [:show, :edit, :update]
    resources :users, except: [:show]
    resources :trashes, only: [:index, :edit, :destroy]
  end

  resources :articles, only: [:show]
  resources :categories, only: [:index, :show]

  get "popular" => "categories#index"
  get "device" => "static_pages#device"
  get "test" => "static_pages#google"
  get "test3" => "static_pages#google3"
  get "test2" => "static_pages#google2"
  get "article_banner" => "static_pages#article_banner"
  get "right_banner" => "static_pages#right_banner"
  get "advertising" => "static_pages#advertising"

  devise_for :users
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
  layout "admin/application"
  before_action :authenticate_user!
  before_action :find_user_by_params, only: [:show, :edit, :update]
  before_action only: [:edit, :update] do
    correct_user? @user
  end

  def show
  end

  def edit
  end

  def update
    @user.update_with_password user_params
    flash.now[:notice] = flash_message("updated")
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :current_password, :avatar,
      :avatar_cache
  end

  def find_user_by_params
    @user = User.find params[:id]
  end
end

app/views/admin/profiles/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for [:admin, @user], url: admin_profile_path, remote: true,
      html: {multipart: true} do |f| %>
      <%= render "shared/errors_messages", object: @user %>
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name, class: "form-control" %></p>
      <p><%= f.label :email %></p>
      <p><%= f.text_field :email, class: "form-control" %></p>
      <p><%= f.label :current_password %></p>
      <p><%= f.password_field :current_password, class: "form-control" %></p>
      <p><%= f.label :avatar %></p>
      <p>
        <%= image_tag @user.avatar_url, class: "img-circle avatar" %>
        <%= f.file_field :avatar, class: "form-control" %>
        <%= f.hidden_field :avatar_cache %>
      </p>
      <hr>
      <%= f.submit t("user.admin.buttons.save"), class: "btn btn-primary pull-right" %>
      <button type="button" class="btn btn-default pull-right btn-close" data-dismiss="modal">
        <%= t "admin.buttons.close" %>
      </button>
    <% end %>
  </div>
</div>

app/views/admin/profiles/_form_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><%= t "user.admin.modal.edit_profile" %></h4>
    </div>
    <div class="modal-body">
      <div class="error_messages"></div>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/profiles/_profile.html.erb
 <div class="col-md-2">
    <%= image_tag @user.avatar_url, class: "img-circle" %>
  </div>
  <div class="col-md-5">
    <table>
      <tr>
        <td><b><%= t "user.admin.list.header.name" %>: </b></td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td><b><%= t "user.admin.list.header.email" %>: </b></td>
        <td><%= @user.email %></td>
      </tr>
    </table>
    <br>
    <% if current_user? @user %>
      <p>
        <%= link_to edit_admin_profile_path(@user), remote: true do %>
          <i class="fa fa-user"></i>
          <%= t("user.admin.actions.edit_profile") %>
        <% end %>
        <br>
        <%= link_to edit_admin_password_path(@user), remote: true do %>
          <i class="fa fa-cog"></i>
          <%= t("user.admin.actions.change_password") %>
        <% end %>
      </p>
    <% end %>
  </div>

app/views/admin/profiles/edit.js.erb
$("#profile-modal").html("<%= escape_javascript(render 'form_modal') %>")
$("#profile-modal").modal("show")

app/views/admin/profiles/show.html.erb
<%= provide :title, t("user.admin.profile") %>
<div class="row">
  <h3><%= t "user.admin.profile" %></h3>
  <hr>
  <div class="flash"></div>
  <div class="profile">
    <%= render "profile" %>
  </div>
</div>
<div class="modal fade" id="profile-modal" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/admin/profiles/update.js.erb
<% if @user.errors.any?  %>
  $(".error_messages").html("<%= j render 'shared/errors_messages', object: @user %>");
<% else %>
  $("#profile-modal").modal("hide");
  $(".profile").html("<%= j render 'profile' %>")
  $(".flash").html("<%= j render 'shared/flash'  %>");
<% end %>