config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root to: "dashboards#index"
    resources :articles, except: [:show]
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :notifications, only: [:index, :new, :create, :destroy]
    resources :passwords, only: [:edit, :update]
    resources :profiles, only: [:show, :edit, :update]
    resources :users, except: [:show]
    resources :trashes, only: [:index, :edit, :destroy]
  end

  resources :articles, only: [:show]
  resources :categories, only: [:index, :show]

  get "popular" => "categories#index"
  get "device" => "static_pages#device"
  get "test" => "static_pages#google"
  get "test3" => "static_pages#google3"
  get "test2" => "static_pages#google2"
  get "article_banner" => "static_pages#article_banner"
  get "right_banner" => "static_pages#right_banner"
  get "advertising" => "static_pages#advertising"

  devise_for :users
end

app/views/layouts/admin/_navigation_menu.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
      <%= link_to t("admin.titles.header"), admin_root_path, class: "navbar-brand" %>
  </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= image_tag current_user.avatar_url, class: "img-circle", width: "30px" %>
          &nbsp; <%= current_user.name %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t("admin.menus.profile"), admin_profile_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to t("admin.menus.logout"), destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">
        <li class="<%= active? "dashboards" %>">
          <%= link_to t("admin.menus.dashboard"), admin_dashboards_path %>
        </li>
        <li class="<%= active? "users" %>">
          <%= link_to t("admin.menus.user"), admin_users_path %>
        </li>
        <li class="<%= active? "categories" %>">
          <%= link_to t("admin.menus.category"), admin_categories_path %>
        </li>
        <li class="<%= active? "articles" %>">
          <%= link_to t("admin.menus.article"), admin_articles_path %>
        </li>
        <li class="<%= active? "trashes" %>">
          <%= link_to t("admin.menus.trash"), admin_trashes_path %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "logo.png" %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Hanuman' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="wrapper">
    <%= render "layouts/admin/navigation_menu" %>
    <div id="page-wrapper">
        <div class="container-fluid">
          <%= render "shared/flash" %>
          <%= yield %>
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
  </div>
  <!-- /#wrapper -->
</body>
</html>