config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  mount Ckeditor::Engine => "/ckeditor"
  namespace :admin do
    root to: "dashboards#index"
    resources :articles, except: [:show]
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :notifications, only: [:index, :new, :create, :destroy]
    resources :passwords, only: [:edit, :update]
    resources :profiles, only: [:show, :edit, :update]
    resources :users, except: [:show]
    resources :trashes, only: [:index, :edit, :destroy]
  end

  resources :articles, only: [:show]
  resources :categories, only: [:index, :show]

  get "popular" => "categories#index"
  get "device" => "static_pages#device"
  get "test" => "static_pages#google"
  get "test3" => "static_pages#google3"
  get "test2" => "static_pages#google2"
  get "article_banner" => "static_pages#article_banner"
  get "right_banner" => "static_pages#right_banner"
  get "advertising" => "static_pages#advertising"

  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :notifications

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true

  def role
    if admin?
      Settings.admin.true
    else
      Settings.admin.false
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin/application"
  before_action :authenticate_user!
  before_action :admin_user, except: [:index]
  before_action :find_user_by_params, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: Settings.per_page)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.save
    @users = User.all
    flash.now[:notice] = flash_message("created")
  end

  def edit
  end

  def update
    @user.update_attributes user_params
    @users = User.all
    flash.now[:notice] = flash_message("updated")
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: flash_message("deleted")
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation,
      :admin
  end

  def find_user_by_params
    @user = User.find params[:id]
  end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for [:admin, @user], remote: true do |f| %>
      <%= render "shared/errors_messages", object: @user %>
      <% if Settings.actions.new_action == action %>
        <p><%= f.label :name %></p>
        <p><%= f.text_field :name, class: "form-control" %></p>
        <p><%= f.label :email %></p>
        <p><%= f.text_field :email, class: "form-control" %></p>
        <p><%= f.label :password %></p>
        <p><%= f.password_field :password, class: "form-control" %></p>
        <p><%= f.label :password_confirmation %></p>
        <p><%= f.password_field :password_confirmation, class: "form-control" %></p>
      <% end %>
      <p><%= f.label :role %></p>
      <p><%= f.collection_select :admin, Settings.admin, :first, :last, {},
        class: "form-control" %></p>
      <hr>
      <%= f.submit t("user.admin.buttons.save"), class: "btn btn-primary pull-right" %>
      <button type="button" class="btn btn-default pull-right btn-close" data-dismiss="modal">
        <%= t "admin.buttons.close" %>
      </button>
    <% end %>
  </div>
</div>

app/views/admin/users/_form_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">
        <% if @user.new_record? %>
          <%= t "user.admin.modal.user_add" %>
        <% else %>
          <%= t "user.admin.modal.user_edit" %>
        <% end %>
      </h4>
    </div>
    <div class="modal-body">
      <div class="error_messages"></div>
      <%= render "form", action: action %>
    </div>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= link_to user.name, admin_profile_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td align="right">
    <% if current_user.admin? %>
      <% unless current_user? user %>
        <%= link_to edit_admin_user_path(user), remote: true, class: "btn-icon" do %>
          <i class="fa fa-pencil-square-o"></i>
          <%= t("user.admin.actions.edit") %>
        <% end %>
        <%= link_to admin_user_path(user), method: :delete,
          data:{confirm: t("custom.confirm_delete")} do %>
          <i class="fa fa-trash-o"></i>
          <%= t("user.admin.actions.delete") %>
        <% end %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/users/create.js.erb
<% if @user.errors.any?  %>
  $(".error_messages").html("<%= j render 'shared/errors_messages', object: @user %>");
<% else %>
  $("#user-modal").modal("hide");
  $(".user-list").html("<%= j render @users %>")
  $(".flash").html("<%= j render 'shared/flash'  %>");
<% end %>

app/views/admin/users/edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'form_modal', action: Settings.actions.edit) %>")
$("#user-modal").modal("show")

app/views/admin/users/index.html.erb
<%= provide :title, t("user.admin.titles.all") %>
<div id="categories">
  <h2 class="title">
    <%= t "user.admin.titles.all" %>
    <% if current_user.admin? %>
      <%= link_to new_admin_user_path, remote: true, class: "btn btn-primary pull-right"  do %>
        <i class="fa fa-plus-square"></i> &nbsp;
        <%= t("user.admin.buttons.add") %>
      <% end %>
    <% end %>
  </h2>
  <hr>
  <div class="flash"></div>
  <table class="table">
    <thead>
      <th><%= t "user.admin.list.header.name" %></th>
      <th><%= t "user.admin.list.header.email" %></th>
      <th><%= t "user.admin.list.header.role" %></th>
      <th></th>
    </thead>
    <tbody class="user-list">
      <%= render @users %>
    </tbody>
  </table>
  <%= will_paginate @users %>
</div>
<div class="modal fade" id="user-modal" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/admin/users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'form_modal', action: Settings.actions.new_action) %>")
$("#user-modal").modal("show")

app/views/admin/users/update.js.erb
<% if @user.errors.any?  %>
  $(".error_messages").html("<%= j render 'shared/errors_messages', object: @user %>");
<% else %>
  $("#user-modal").modal("hide");
  $(".user-list").html("<%= j render @users %>")
  $(".flash").html("<%= j render 'shared/flash'  %>");
<% end %>